Add xhprof 2.2.0
kabel/homebrew-pecl pull request #9
Opened 2020-07-29 15:34 UTC by glensc

2020-07-29 15:44 UTC, glensc commented
I wonder what's wrong?

```
➔ brew install php@7.3-xhprof
==> Installing php@7.3-xhprof from kabel/pecl
==> Downloading https://pecl.php.net/get/xhprof-2.2.0.tgz
Already downloaded: /Users/glen/Library/Caches/Homebrew/downloads/f19bf6b21bfc92df76def4d1b844282968f2d5caf5670704c4b53ad3b6e71a6d--xhprof-2.2.0.tgz
==> /usr/local/opt/php@7.3/bin/phpize
Last 15 lines from /Users/glen/Library/Logs/Homebrew/php@7.3-xhprof/01.phpize:
2020-07-29 18:43:09 +0300

/usr/local/opt/php@7.3/bin/phpize

Cannot find config.m4.
Make sure that you run '/usr/local/opt/php@7.3/bin/phpize' in the top level source directory of the module


If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/kabel/homebrew-pecl/issues
```

2020-07-29 15:45 UTC, glensc commented
ok need to enter 'extension' subdir:

```
bash-3.2$ ls
CHANGELOG       CREDITS         LICENSE         README.md       examples        extension       xhprof_html     xhprof_lib
bash-3.2$ cd extension/
bash-3.2$ ls
config.m4       config.w32      php_xhprof.h    tests           xhprof.c
bash-3.2$
```

2020-07-29 19:16 UTC, glensc commented
@kabel the ci fails with "No license specified for package":
- https://dev.azure.com/kevinabel0613/kevinabel/_build/results?buildId=263&view=logs&jobId=c6ade96f-589d-5e19-3e18-3629e97f959d&j=c6ade96f-589d-5e19-3e18-3629e97f959d&t=dcc0016f-d3fe-5c84-871e-f3eb026f9629

but I don't see any other formula specifying the license...

2020-07-29 19:26 UTC, kabel commented
Probably a new rubocop from brew core. I'll take a look later.

2020-07-29 19:48 UTC, kabel requested changes
Homebrew core is rolling out requirements for licenses on all formulae. The source is licensed at `Apache-2.0` on the SPDX list.

2020-07-29 19:48 UTC, kabel commented on Formula/php-xhprof.rb
> +  sha256 "034b3141411f3aaf44f91a0ec86a5f4c805a9372c4ef4f9c5ba38ef0b56f4fa2"
```suggestion
  sha256 "034b3141411f3aaf44f91a0ec86a5f4c805a9372c4ef4f9c5ba38ef0b56f4fa2"
  license "Apache-2.0"
```

2020-07-29 19:48 UTC, kabel commented on Formula/php@7.2-xhprof.rb
> +  sha256 "034b3141411f3aaf44f91a0ec86a5f4c805a9372c4ef4f9c5ba38ef0b56f4fa2"
```suggestion
  sha256 "034b3141411f3aaf44f91a0ec86a5f4c805a9372c4ef4f9c5ba38ef0b56f4fa2"
  license "Apache-2.0"
```

2020-07-29 19:48 UTC, kabel commented on Formula/php@7.3-xhprof.rb
> +  sha256 "034b3141411f3aaf44f91a0ec86a5f4c805a9372c4ef4f9c5ba38ef0b56f4fa2"
```suggestion
  sha256 "034b3141411f3aaf44f91a0ec86a5f4c805a9372c4ef4f9c5ba38ef0b56f4fa2"
  license "Apache-2.0"
```

2020-07-30 03:21 UTC, kabel commented
Squash merged at 7f14d0c9602ed80cd1141f5f3d8cfca78dd69b95. Don't know what I messed up for GitHub to not recognize auto-merge.

2020-07-30 03:21 UTC, closed without merging